apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order-api.fullname" . }}-config
  labels:
    {{- include "order-api.labels" . | nindent 4 }}
data:
  APP_NAME: {{ include "order-api.fullname" . | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  AWS_REGION: {{ .Values.awsRegion | quote }}
  LAMBDA_FUNCTION_NAME: {{ .Values.lambdaFunctionName | quote }}
